name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ROS 2 Humble
        run: |
          sudo apt update
          sudo apt install -y curl gnupg2 lsb-release
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions
      - name: Build and Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
          timeout 60 ros2 run mypkg resource_monitor > /tmp/mypkg.log
          grep 'Published:' /tmp/mypkg.log
