jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # ROS 2 Humbleのセットアップ
      - name: Set up ROS 2 Humble
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -c | awk "{print $2}") main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt update
          sudo apt install ros-humble-desktop

      # ROS 2 Jazzyのセットアップ
      - name: Set up ROS 2 Jazzy
        run: |
          sudo apt install ros-jazzy-desktop
          source /opt/ros/jazzy/setup.bash

      # 両方の環境を使ったテストスクリプト実行
      - name: Run test.bash for Jazzy
        run: |
          source /opt/ros/jazzy/setup.bash
          bash ./src/mypkg/test/test.bash

      - name: Run test.bash for Humble
        run: |
          source /opt/ros/humble/setup.bash
          bash ./src/mypkg/test/test.bash

