name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure directories and permissions
        run: |
          mkdir -p /root/ros2_ws/src/mypkg
          chmod +x ./src/mypkg/test/test.bash
      - name: Sync files
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
      - name: Build and Test
        run: |
          cd /root/ros2_ws
          bash ./src/mypkg/test/test.bash /root

